# Generated by Django 5.1.7 on 2025-07-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificacion",
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
            },
        ),
    ]
