# Generated by Django 5.1.7 on 2025-08-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cita_confirmada', 'Cita Confirmada'), ('cita_cancelada', 'Cita Cancelada'), ('cita_reagendada', 'Cita Reagendada'), ('mensaje', 'Mensaje'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
