# Generated by Django 5.2.1 on 2025-07-29 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edadMin', models.IntegerField()),
                ('edadMax', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
            },
        ),
        migrations.CreateModel(
            name='GrupoDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apMaterno', models.CharField(max_length=100)),
                ('apPaterno', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('estadoCivil', models.CharField(max_length=20)),
                ('tipoSangre', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.categoria')),
                ('deportes', models.ManyToManyField(related_name='atletas', to='catalogos.deporte')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
        migrations.CreateModel(
            name='AtletaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('calle', models.CharField(max_length=255)),
                ('noExterior', models.CharField(blank=True, max_length=10, null=True)),
                ('noInterior', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('atleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogos.atleta')),
            ],
            options={
                'verbose_name': 'Contacto de Atleta',
                'verbose_name_plural': 'Contactos de Atleta',
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('areas', models.ManyToManyField(related_name='consultorios', to='catalogos.area')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apPaterno', models.CharField(max_length=100)),
                ('apMaterno', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('telefono', models.CharField(max_length=15)),
                ('disciplinas', models.ManyToManyField(related_name='entrenadores', to='catalogos.deporte')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
            },
        ),
        migrations.AddField(
            model_name='deporte',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deportes', to='catalogos.grupodeportivo'),
        ),
        migrations.CreateModel(
            name='Metodologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('aPaterno', models.CharField(max_length=100)),
                ('aMaterno', models.CharField(max_length=100)),
                ('deportes', models.ManyToManyField(related_name='metodologos', to='catalogos.deporte')),
                ('grupos', models.ManyToManyField(related_name='metodologos', to='catalogos.grupodeportivo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesionalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('idArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional de la Salud',
                'verbose_name_plural': 'Profesionales de la Salud',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_cita', models.PositiveIntegerField(default=30)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.consultorio')),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_semana', models.JSONField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.consultorio')),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Horario Temporal',
                'verbose_name_plural': 'Horarios Temporales',
            },
        ),
        migrations.CreateModel(
            name='ProgramaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('básico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50)),
                ('objetivo', models.CharField(max_length=100)),
                ('duracion_dias', models.IntegerField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='PlanesEntrenamiento/%Y/%m/%d/')),
                ('deporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.deporte')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_entrenamiento', to='catalogos.entrenador')),
            ],
            options={
                'verbose_name': 'Programa de Entrenamiento',
                'verbose_name_plural': 'Programas de Entrenamiento',
            },
        ),
        migrations.CreateModel(
            name='ResponsableAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.atleta')),
            ],
            options={
                'verbose_name': 'Responsable de Atleta',
                'verbose_name_plural': 'Responsables de Atletas',
            },
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(help_text='Día relativo al inicio del programa')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='catalogos.programaentrenamiento')),
            ],
            options={
                'verbose_name': 'Sesión de entrenamiento',
                'verbose_name_plural': 'Sesiones de entrenamiento',
                'ordering': ['programa', 'dia'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('distancia_metros', models.FloatField(blank=True, null=True)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='catalogos.sesionentrenamiento')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['sesion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SlotDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_disponibles', to='catalogos.area')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_disponibles', to='catalogos.consultorio')),
                ('profesional_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Cita Disponible',
                'verbose_name_plural': 'Citas Disponibles',
            },
        ),
    ]
