# Generated by Django 5.2.1 on 2025-07-29 01:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_area', to='catalogos.area')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_atleta', to='catalogos.atleta')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_consultorio', to='catalogos.consultorio')),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_profesional', to='catalogos.profesionalsalud')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citas_slot', to='catalogos.slotdisponible')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('antecedentes_familiares', models.TextField(blank=True, null=True)),
                ('antecedentes_no_patologicos', models.TextField(blank=True, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia_cardiaca', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia_respiratoria', models.CharField(blank=True, max_length=20, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=10, null=True)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='catalogos.atleta')),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulos.cita')),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudio', models.CharField(choices=[('LAB', 'Análisis de Laboratorio'), ('IMG', 'Estudio de Imagen'), ('CAR', 'Cardiología'), ('NEU', 'Neurológico'), ('ODO', 'Odontológico'), ('OFT', 'Oftalmológico'), ('OTR', 'Otros')], max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('resultado', models.TextField()),
                ('fecha_realizacion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='estudios/%Y/%m/%d/')),
                ('enlace', models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='modulos.consulta')),
            ],
            options={
                'verbose_name': 'Estudio Médico',
                'verbose_name_plural': 'Estudios Médicos',
                'ordering': ['-fecha_realizacion'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_asignados', to='catalogos.atleta')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='catalogos.programaentrenamiento')),
            ],
            options={
                'verbose_name': 'Asignación de programa',
                'verbose_name_plural': 'Asignación de programas',
            },
        ),
    ]
