"""
Django settings for SportCareIdet project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ff#tgg&$mvzd^g86w379=^eub^sc4rl8hh)@oms7lk^f=dy4(-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'backend', '*']


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",         # Filtros avanzados (opcional)
    "unfold.contrib.forms",           # Formularios estilizados (opcional)
    "unfold.contrib.inlines",         # Inlines con tabs (opcional)
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'catalogos',
    'rest_framework_simplejwt',
    'modulos',
    'notificaciones',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # el cors headers xd
    'corsheaders.middleware.CorsMiddleware',     
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'catalogos.middleware.SlotCleanupMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

ROOT_URLCONF = 'SportCareIdet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SportCareIdet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'SportCareIdet',
        'USER': 'postgres',
        'PASSWORD': '23570',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'connect_timeout': 5,  # Tiempo de espera para conexión (segundos)
              # Para producción con SSL
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploaded files)
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR  # Cambiar para que apunte al directorio base del proyecto

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración CORS mejorada
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://react-app:80" ,
]

CORS_ALLOW_CREDENTIALS = True

# Permitir headers adicionales para las APIs
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

UNFOLD = {
    "SITE_HEADER": "SportCareIdet",
    "SITE_TITLE": "Portal de Administración SportCare",
    "SITE_URL": "/",
    # "FAVICON": "path/to/favicon.ico", # Descomenta y ajusta si tienes un favicon

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False, # Oculta la lista por defecto para usar solo nuestra navegación
        "navigation": [
            {
                "title": "Gestión Principal",
                "icon": "dashboard",
                "items": [
                    {
                        "title": "Atletas",
                        "icon": "directions_run",
                        "link": "/admin/catalogos/atleta/",
                    },
                    {
                        "title": "Agendar Citas",
                        "icon": "event",
                        "link": "/admin/modulos/cita/",
                    },
                     {
                        "title": "Programas Asignados",
                        "icon": "assignment_turned_in",
                        "link": "admin/modulos/programaasignado/",
                    },
                    {
                        "title": "Usuarios",
                        "icon": "people",
                        "link": "auth/user/",
                    },
                    {
                        "title": "Grupos",
                        "icon": "group",
                        "link": "auth/group/",
                    },
                    {
                        "title": "Metodológos",
                        "icon": "people",
                        "link": "/admin/catalogos/metodologo/",
                    },
                ],
            },
            {
                "title": "Expedientes y Salud",
                "icon": "medical_services",
                "items": [
                    {
                        "title": "Consultas Médicas",
                        "icon": "description",
                        "link": "/admin/modulos/consulta/",
                    },
                   
                    {
                        "title": "Profesionales de Salud",
                        "icon": "health_and_safety",
                        "link": "/admin/catalogos/profesionalsalud/",
                    },
                    {
                        "title": "Consultorios",
                        "icon": "local_hospital",
                        "link": "/admin/catalogos/consultorio/",
                    },
                    {
                        "title": "Horarios",
                        "icon": "schedule",
                        "link": "/admin/catalogos/horario/",
                    },
                    {
                        "title": "Horarios Temporales",
                        "icon": "schedule",
                        "link": "/admin/catalogos/slotdisponible/",
                    },
                ],
            },
            {
                "title": "Entrenamiento y Deporte",
                "icon": "fitness_center",
                "items": [
                    {
                        "title": "Programas de Entrenamiento",
                        "icon": "assignment",
                        "link": "/admin/catalogos/programaentrenamiento/",
                    },
                    {
                        "title": "Entrenadores",
                        "icon": "sports",
                        "link": "/admin/catalogos/entrenador/",
                    },
                     {
                        "title": "Deportes",
                        "icon": "sports_soccer",
                        "link": "/admin/catalogos/deporte/",
                    },
                     {
                        "title": "Grupo deportivo",
                        "icon": "sports_soccer",
                        "link": "/admin/catalogos/grupodeportivo/",
                    },
                ],
            },
            {
                "title": "Configuración y Catálogos",
                "icon": "settings",
                "items": [
                    {
                        "title": "Áreas Médicas",
                        "icon": "category",
                        "link": "/admin/catalogos/area/",
                    },
                    {
                        "title": "Categorías por Edad",
                        "icon": "cake",
                        "link": "/admin/catalogos/categoria/",
                    },
                     {
                        "title": "Estudios Médicos",
                        "icon": "description",
                        "link": "/admin/modulos/estudio/",
                    },
                    {
                        "title": "Contactos de Atletas",
                        "icon": "fitness_center",
                        "link": "/admin/catalogos/atletacontacto/",
                    },
                    # Modelos como Estudio, Ejercicio, AtletaContacto, etc.,
                    # suelen administrarse mejor como "inlines" dentro de sus
                    # modelos principales (Consulta, SesionEntrenamiento, Atleta)
                    # y no necesitan un enlace directo en el menú lateral.
                ],
            },
        ],
    },

}


# Configuración de Email con Maileroo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.maileroo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'SportCareIdet@9c910bee8c73c5a2.maileroo.org'
EMAIL_HOST_PASSWORD = '7b2cffc48077198a94710309881394bd75a61a383f7cba063507ae274c194cf0'  
DEFAULT_FROM_EMAIL = 'SportCare IDET <SportCareIdet@9c910bee8c73c5a2.maileroo.org>'

# URLs del Frontend para los enlaces de recuperación
FRONTEND_URL = 'http://localhost:5173'  # Sin la ruta específica
PASSWORD_RESET_TIMEOUT = 3600  # 1 hora en segundos

# Agregar configuración de logging para debug
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'usuarios': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
# settings.py
# ... al final del archivo

MAILEROO_API_KEY = '7b2cffc48077198a94710309881394bd75a61a383f7cba063507ae274c194cf0'